### ISSUE TITLE
How can i encoding and decode array of bytes (Buffer)

### ISSUE THREAD

**Issue by BahgatMashaly** [cgraumann/iLBC2PCM.NET#1]
How can i encoding and decode array of byte (Buffer) using iLBC  during recording audio

**Comment by cgraumann** [comment]
Hi,
I haven't worked on this for quite a time so I'd need to look into the project again and will come back to your question later. Meanwhile you might explain more explicitly what you are planning to do?
Cheers

**Comment by cgraumann** [comment]
Closed due to inactivity of the submitter.
